# -*- coding: utf-8 -*-
"""Oppgave_1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ic-o7Zr3Qvmo22gLeIALskiATCJCVzrL

Oppgave 1a
"""

import numpy as np
x = 1
y = 2
z = 3

Omega = np.array([[0,-z,y],[z,0,-x],[-y,x,0]])

def I :

def E(Omega, h) :
  I = np.identity(Omega.shape[0])
  omega = np.sqrt(Omega[0][1]**2+Omega[0][2]**2+Omega[1][2]**2)

  return I + (1-np.cos(h*omega))*(Omega/omega)**2 + np.sin(h*omega)*(Omega/omega)

h = 0
E(Omega, h).transpose()*E(Omega, h)

"""Oppgave 1b"""

def Erot(I, rotVek) :
  L = np.dot(I, rotVek)
  return (1/2)*np.dot(L, rotVek)

rotVek = np.array([1,1,1])
I = 3
Erot(I, rotVek)

"""Oppgave 1c"""

def Ixx():
  return ((M_1*R_2**2)/4) + ((M_1*L_1**2)/12) + ((M_2*R_2**2)/2)

def Iyy():
  return (M_1*R_1**2) + ((M_2*L_2)/4) + ((M_1*R_1**2)/2) + ((M_2*R_2**2)/4) + ((M_2L_2**2)/12)

def Izz():
    return (M_1*R_1**2) + ((M_2*L_2)/4) + ((M_1*R_1**2)/4) + ((M_1L_1**2)/12) + ((M_2*R_2**2)/4) + ((M_2L_2**2)/12)

L_1 = 0.08
R_1 = 0.01

L_2 = 0.04
R_2 = 0.01

p = 6.7
x1 = -1.0
x2 = 2.0

M_1 = 253.0/2
M_2 = 253.0/2

Ixx = M_1*(R_1**2)/4 + M_1*(L_1**2)/12 + M_2*(R_2**2)/2

Iyy = M_1*(R_1**2) + M_2*L_2/4 + M_1*(R_1**2)/2 + M_2*(R_2**2)/4 + M_2*(L_2**2)/12

Izz = M_1*(R_1**2) + M_2*L_2/4 + M_1*(R_1**2)/4 + M_1*(L_1**2)/12 + M_2*(R_2**2)/4 + M_2*(L_2**2)/12

print(Ixx)
print(Iyy)
print(Izz)